### ISSUE TITLE
Thank you for this great package

### ISSUE THREAD

**Issue by mholt** [dsnet/compress#55]
(This is not a bug, you may close the issue.) I'm still on the edge of my seat for brotli write support, but in the meantime I have found the bzip2 writer [very useful](https://github.com/mholt/archiver/commit/fb2abc6fe6cc46617ca01ca2bb02e57b42ff105a). Thank you for writing this package! Looking forward to its completion.

**Comment by dsnet** [comment]
Hey Matt, thanks so much for the kind words.

I noticed a sudden increase in traffic to this package, did something happen that's driving everyone here?

For the most part, I've been trying to keep a low profile while I keep working on the repo, but I certainly don't mind users motivating me to keep working on this :)

On my [`development` branch](https://github.com/dsnet/compress/tree/development) where I've been doing most of the recent updates, I've change the API from:
```go
NewReader(io.Reader) *Reader
NewWriter(io.Writer) *Writer
```
to:
```go
// A nil Config uses the default settings to create the Reader or Writer and is guaranteed to not fail.
NewReader(io.Reader, *ReaderConfig) (*Reader, error)
NewWriter(io.Writer, *WriterConfig) (*Writer, error)
```
The use of a Config struct allows for future customizations without resorting to NewReaderX, NewReaderY, NewReaderZ, for every permutation of configuration.

I was hoping to make that change in the `master` branch since there were no users of any of my packages not long ago. Are you okay with me making the API change on the `master` branch while it is still early?

**Comment by mholt** [comment]
Yes! My preference is if you're going to break it, do it early.

Really glad you're still able to work on it. :) Didn't know about that development branch, I'll keep an eye out!
