### ISSUE TITLE
Did you force push on your master branch?

### ISSUE THREAD

**Issue by JelteF** [dsnet/compress#61]
I had pinned this commit using [`dep`](https://github.com/golang/dep/): c4dbed65594871659ea7347a85e1b8dcd97b9990

And suddenly it doesn't exist on the master branch anymore.

**Comment by dsnet** [comment]
I apologize for that. I was trying to setup Travis CI and accidentally switched from the `development` branch to the `master` branch and pushed a rebase of the `development` branch on `master`.

The affected history is: https://github.com/dsnet/compress/compare/bcd0d8906d9a6df7644892b456e94d2abbbb5177...c57be8a27eb955bb314e404d40f9adde726dc6c8. The changes prior to Dec 7 are identical to the old history, but their hashes are different (since they were originally added using `git cherry-pick`). The changes on Dec 7 are all the new changes I added for Travis support.

I've taken measures to prevent this in the future by enabling GitHub's branch protection on `master`.

**Comment by dsnet** [comment]
I'm to close this since the measures taken should be sufficient to prevent in the future.
